version: '3'
services:
  sound-wire-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sound-wire-query-server
    tty: true
    ports:
      - "${CLIENT_PORT}:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app